### ISSUE TITLE
Add support for non-root ZFS

### ISSUE THREAD

**Issue by hmoffatt** [Freaky/zfsnapr#2]
I'm getting the following error running `zfsnapr mount /mnt/backup`:
```
filesystem 'tank/enc/home@zfsnapr-1c75b7844c163f99' cannot be mounted at '/mnt/backup/home' due to canonicalization error: No such file or directory
```

I have the following ZFS datasets:
```
root@backupdroid:~# zfs list
NAME                     USED  AVAIL     REFER  MOUNTPOINT
tank                    1.22T  1.41T       96K  /tank
tank/enc                 297G  1.41T      248K  /tank/enc
tank/enc/home            182G  1.41T      182G  /home
tank/enc/time_machine    114G  1.41T      114G  /tank/enc/time_machine
```

If I pre-create /mnt/backup/home and /mnt/backup/tank it works.

My system isn't pure ZFS (the root is ext4), so it might be that it fails the pre-requisites in the readme.

**Comment by Freaky** [comment]
Yep - with a ZFS root, that would be mounted first and would contain your /home and /tank directories to recursively mount the others on.  Without that, you need to create those directories by hand - I'm glad that works!

Doing this automatically would be nice - I guess ideally on a tmpfs so as to leave the target directory physically untouched.  This approach would also generalise nicely and allow other functionality that avoids mounting the full ZFS hierarchy.

**Comment by hmoffatt** [comment]
The workaround is fine for me. Thanks for your help and thanks for this tool!

**Comment by Freaky** [comment]
f15e9bd should fix this - I can exclude my root pool and still mount other pools.
